project_name: osc-record
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: danielbrodie
    name: osc-record
